Homework 3
fintech-kotlin/erohin-cashback-service pull request #3
Opened 2020-03-10 12:53 UTC by aedev

# Выполнено задание № 3

## В процесс было сделано:
 - Реализован Consumer Kafka
 - Реализован метод TransactionService.process
 - Исправлены ошибки

## PR чеклист:
 - [ ] В Project выставлен `Tinkoff "Java to Kotlin"`
 - [ ] Добавлен label с номером домашнего задания

2020-03-10 17:11 UTC, romanov-ivan requested changes
В целом совсем критичных замечаний нет, если есть желание, можно поправить какие-то из комментариев. Желательно попробовать вынести `RestTemplate` и упростить сигнатуру класса `TransactionListener`

2020-03-10 17:11 UTC, romanov-ivan commented on src/main/kotlin/ru/tinkoff/fintech/listener/TransactionListener.kt
> +class TransactionListener @Autowired constructor(
Начиная со Spring 4.3 аннотацию `@Autowired` можно опустить в спринговом бине с единственным конструктором, и декларация такого компонента может выглядеть компактнее
```
class TransactionListener(private val transactionService: TransactionService) {
```

2020-03-10 17:11 UTC, romanov-ivan commented on src/main/kotlin/ru/tinkoff/fintech/listener/TransactionListener.kt
> +    fun onMessage(message: String) {
Можно сразу же типизировать принимаемое сообщение и не вызывать objectMapper вручную
```
@KafkaListener(topics = ["\${paimentprocessing.kafka.consumer.topic}"])
fun onMessage(@Payload transaction: Transaction) {
    try {
            transactionService.process(transaction)
        } catch (e: Exception) {
            LOGGER.info("Сообщение не удалось обработать" , e)
        }
}
```
плюс для этого необходимо скофигурировать бин с типом ObjectMapper по аналогии с тем, что у тебя конфигурируется в методе getObjectMapper()

Сейчас не обязательно менять, информация на будущее

2020-03-10 17:11 UTC, romanov-ivan commented on src/main/kotlin/ru/tinkoff/fintech/util/Util.kt
> +            return getObjectMapper().readValue(str, Transaction::class.java)
Создание ObjectMapper каждый раз - тяжелая операция, из-за этого может просесть перфоманс всего приложения, учитывая, что мы читаем много транзакций. Поэтому нужно сделать singleton который будет хранить инстанст, лучше всего спринговый бин с типом `ObjectMapper`.

2020-03-10 17:11 UTC, romanov-ivan commented on src/main/kotlin/ru/tinkoff/fintech/client/CardServiceClientImpl.kt
> +        val response = RestTemplate().getForEntity("$uri/$id", Card::class.java)
`RestTemplate` не стоит создавать на каждый вызов. Лучше сделать его бином и инджектить в каждый из клиентов.
Плюс, надо не забывать устанавливать таймауты вызова, чтобы приложение не висело очень долго, в случае проблем на стороне сервиса.

Пример конфигурации RestTemplate
```
@Configuration
public class RestConfiguration {

    @Bean
    fun myRestTemplate(
        restTemplateBuilder: RestTemplateBuilder
    ): RestTemplate = restTemplateBuilder
        .setConnectTimeout(Duration.ofSeconds(30))
        .setReadTimeout(Duration.ofSeconds(30))
        .build()
}
```

2020-03-10 20:17 UTC, aedev commented
@romanov-ivan  Спасибо за комментарии. Внес изменения.

2020-03-10 20:29 UTC, aedev commented on src/main/kotlin/ru/tinkoff/fintech/listener/TransactionListener.kt
> +    fun onMessage(message: String) {
я пытался типизировать значение. 
Как я понимаю нужно в application.yml добавить
`spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  spring.kafka.consumer.value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer`
и скофигурировать бин с типом ObjectMapper.
У меня ничего не вышло и я решил пойти по легкому пути.

2020-03-11 09:18 UTC, romanov-ivan approved these changes
Окей, можно мержить изменения

2020-03-22 10:04 UTC, merged